### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [DanySK/Protelis#9]
Hello Protelis team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the Protelis project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by DanySK** [comment]
Hi @miklossy,
sure we are. @jakebeal I'm also tagging you because this issue got open on my own original repo, while the official fork is Protelis/Protelis.

This would be my suggestion, @jakebeal and @w4bo, as major contributors please let me know if you are ok with this or you want to amend it:

```html
<tr>
	<td><a href="project_link">Protelis</a></td>
	<td>Protelis is a programming language aiming to produce reliable and robust collective behavior from uncoordinated local interactions among an assortment of different potentially mobile devices. Protelis is grounded on the paradigm of <i>aggregate programming</i>, a way of thinking about and decomposing problems that can be solved with a network of distributed sensors and computers.</td>
	<td>GPL with linking exception</td>
	<td>Language</td>
	<td>Danilo Pianini, Jacob Beal, Matteo Francia, and others</td>
</tr>
```

**Comment by miklossy** [comment]
Thank you @DanySK !

**Comment by miklossy** [comment]
The `Protelis` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
